/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Urod;

import java.time.Year;
import java.time.Clock;

/**
 *
 * @author 44785
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }
    //declaring public variables
    public int age, currentYear, result;
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblYOB = new javax.swing.JLabel();
        txtYOB = new javax.swing.JTextField();
        btnCalcAge = new javax.swing.JButton();
        lblAge = new javax.swing.JLabel();

        lblYOB.setText("Enter your Year of Birth");

        txtYOB.setToolTipText("");

        btnCalcAge.setText("Calculate Age");
        btnCalcAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcAgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalcAge)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAge)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblYOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtYOB)))
                        .addGap(156, 530, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(lblYOB)
                .addGap(18, 18, 18)
                .addComponent(txtYOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(btnCalcAge)
                .addGap(38, 38, 38)
                .addComponent(lblAge)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        txtYOB.getAccessibleContext().setAccessibleName("txtYOB");
        btnCalcAge.getAccessibleContext().setAccessibleName("btnCalcAge");
        lblAge.getAccessibleContext().setAccessibleName("lblAge");
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcAgeActionPerformed
        // TODO add your handling code here:
        age =  Integer. parseInt(txtYOB.getText()); //parse int
        Year currentYear = Year.now(Clock.systemUTC()); // function to get current year
        result = Integer.parseInt(currentYear.toString()) - age; // calculation
        lblYOB.setText("Your age is : " + result );
    }//GEN-LAST:event_btnCalcAgeActionPerformed
 public static void main(String[] args) {
    javax.swing.JFrame frame = new javax.swing.JFrame("Convertor");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setContentPane(new NewJPanel());
    frame.pack();
    frame.setVisible(true);
  
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcAge;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblYOB;
    private javax.swing.JTextField txtYOB;
    // End of variables declaration//GEN-END:variables
}
