/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Urod;

import javax.swing.event.DocumentEvent;

/**
 *
 * @author 44785
 */
public class Convertor extends javax.swing.JPanel {

    /**
     * Creates new form Convertor
     */
    public Convertor() {
        initComponents();
          txtAmmount.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(DocumentEvent e){
             calculate();

            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                 calculate();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                 calculate();
            }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEURGBP = new javax.swing.JButton();
        btnGBPEUR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtAmmount = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        lblResult = new javax.swing.JLabel();
        lblAuto = new javax.swing.JLabel();

        btnEURGBP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEURGBP.setText("EUR - to - GBP");
        btnEURGBP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEURGBPActionPerformed(evt);
            }
        });

        btnGBPEUR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGBPEUR.setText("GBP - to - EUR");
        btnGBPEUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGBPEURActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Enter ammount :");

        txtAmmount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAmmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmmountActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblResult.setText("Result :");

        lblAuto.setText("Auto Result :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblResult)
                        .addGap(233, 233, 233)
                        .addComponent(lblAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnExit)
                        .addComponent(btnGBPEUR)
                        .addComponent(btnEURGBP)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAmmount)))
                .addContainerGap(316, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResult)
                    .addComponent(lblAuto))
                .addGap(47, 47, 47)
                .addComponent(btnEURGBP)
                .addGap(60, 60, 60)
                .addComponent(btnGBPEUR)
                .addGap(103, 103, 103)
                .addComponent(btnExit)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        btnEURGBP.getAccessibleContext().setAccessibleName("btnEURGBP");
        btnGBPEUR.getAccessibleContext().setAccessibleName("btnGBPEUR");
        jLabel1.getAccessibleContext().setAccessibleName("txtAmmount");
        txtAmmount.getAccessibleContext().setAccessibleName("txtAmmount");
        btnExit.getAccessibleContext().setAccessibleName("btnExit");
        lblResult.getAccessibleContext().setAccessibleName("lblResult");
        lblAuto.getAccessibleContext().setAccessibleName("lblAuto");

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents
public static double num, rate, result, result2;
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
         System.exit(0); //exit program
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEURGBPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEURGBPActionPerformed
        // TODO add your handling code here:
         num = Double.parseDouble(txtAmmount.getText());
         rate = Double.parseDouble("0.86");
        
         result = num * rate;
         result = Math.round(result * 100.0) / 100.0;
         
         lblResult.setText(String.format("Result : %.2f", result));
    }//GEN-LAST:event_btnEURGBPActionPerformed

    private void btnGBPEURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGBPEURActionPerformed
        // TODO add your handling code here:
         num = Double.parseDouble(txtAmmount.getText());
         rate = Double.parseDouble("1.16");
        
         result = num * rate;
         result = Math.round(result * 100.0) / 100.0;
         
         lblResult.setText(String.format("Result : %.2f", result));
    }//GEN-LAST:event_btnGBPEURActionPerformed

    private void txtAmmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmmountActionPerformed
private void calculate() {
    try {
        double value = Double.parseDouble(txtAmmount.getText());
        double result = value * 0.86;
        double result2 = value * 1.16;
        result = Math.round(result * 100.0) / 100.0;
        result2 = Math.round(result2 * 100.0) / 100.0;
        lblAuto.setText(String.format("Auto Result : %.2fEUR, %.2fGBP", result, result2));
    } catch (NumberFormatException e) {
        lblAuto.setText("Auto Result : ");
    }
}
    public static void main(String[] args) {
    javax.swing.JFrame frame = new javax.swing.JFrame("Convertor");
    frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
    frame.setContentPane(new Convertor());
    frame.pack();
    frame.setVisible(true);
  
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEURGBP;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGBPEUR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAuto;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTextField txtAmmount;
    // End of variables declaration//GEN-END:variables
}
